version: '3.9'

services:

  postgres:
    restart: always
    image: postgres:latest
    
    expose:
    - "5433"
    ports:
    - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      # The environment variable credentials that is needed 
      # in django settings for Postgres to work.
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_HOST

volumes:
  pgdata:
